// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Match Next.js's own .env precedence (.env.local wins over .env) — plain
// `dotenv/config` only reads `.env`, which would silently point the CLI at
// the wrong database if `.env.local` is where real values live.
loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  experimental: {
    // Required by migrations.initShadowDb below.
    externalTables: true,
  },
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
    // The 20260720182734_init_supabase_auth migration creates a trigger on
    // auth.users (Supabase's own schema) — `migrate dev`'s shadow database
    // is a bare Postgres instance without it, so replaying that migration
    // during diffing fails with `schema "auth" does not exist` unless a
    // stub exists for it to attach to. Same problem for
    // 20260727044848_add_mbti_self_motivation_lead_sources, which inserts
    // into storage.buckets and creates a policy on storage.objects (Plan 17)
    // — stub those too, or replaying that migration fails the same way.
    initShadowDb: `
      CREATE SCHEMA IF NOT EXISTS auth;
      CREATE TABLE IF NOT EXISTS auth.users (
        id uuid PRIMARY KEY,
        email text,
        raw_user_meta_data jsonb
      );
      CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid AS $$ SELECT NULL::uuid $$ LANGUAGE sql STABLE;

      CREATE SCHEMA IF NOT EXISTS storage;
      CREATE TABLE IF NOT EXISTS storage.buckets (
        id text PRIMARY KEY,
        name text,
        public boolean
      );
      CREATE TABLE IF NOT EXISTS storage.objects (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        bucket_id text,
        name text
      );
      CREATE OR REPLACE FUNCTION storage.foldername(name text) RETURNS text[] AS $$ SELECT string_to_array(name, '/') $$ LANGUAGE sql STABLE;
    `,
  },
  datasource: {
    // Supabase's pooler (DATABASE_URL) doesn't support the prepared
    // statements `prisma migrate`/`db push` need — the CLI always needs the
    // unpooled connection. The app runtime uses DATABASE_URL directly via
    // the adapter in src/lib/prisma.ts, independent of this config.
    url: process.env["DIRECT_URL"],
  },
});
